# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'SSW_CHAT' do
pod 'RealmSwift', '~> 1.0'
pod 'Realm', '~> 1.0'
pod 'AddressBookKit', '~> 0.1'
pod 'Firebase', '~> 3.4'
pod 'Toast-Swift', '~> 1.3'
pod 'PlayerView', '~> 0.2'
pod 'ReachabilitySwift', '~> 2.3'
pod 'ZipArchive', '~> 1.4'

end

